name: luckcam
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  permission_handler: ^12.0.1
  http: ^1.5.0
  web_socket_channel: ^3.0.3
  flutter_webrtc: ^1.1.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  wakelock_plus: ^1.4.0

  # Sunucu ve Ağ için
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  network_info_plus: ^7.0.0

  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

